version: '2'

services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: node8:local
    volumes:
      - .:/data
    ports:
      - "3001:3001"
    working_dir: /data
    command: ["yarn", "run", "client:start"]

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: node8:local
    volumes:
      - .:/data
    ports:
      - "3000:3000"
    working_dir: /data
    command: ["yarn", "run", "server:start"]


networks:
  default:
    external:
      name: local
