version: '2'

services:
  nginx:
    image: nginx:1.11.10-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  client:
    image: node:12.0.0-alpine
    volumes:
      - .:/data
    ports:
      - 3001:3001
      - 1234:1234
      - 1235:1235
    working_dir: /data
    command: ['npm', 'run', 'dev-client']

  server:
    image: node:12.0.0-alpine
    volumes:
      - .:/data
    ports:
      - '3000:3000'
    working_dir: /data
    command: ['npm', 'run', 'dev-server']

networks:
  default:
    external:
      name: local
